a = input("Entre com um dado: ")
print("É uma palavra? ", a.isalpha())
print("É um número? ", a.isnumeric())
print("Contém apenas espaços? ", a.isspace())
print("Está capitalizado? ", a.istitle())
print("Contém apenas minúsculas? ", a.islower())
print("Contém apenas maiúsculas?", a.isupper())